import type {Metadata} from 'next'
import {Outfit} from 'next/font/google'
import '../styles/globals.scss'

const outfitFont = Outfit({
    weight: ['300', '500', '600'],
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={outfitFont.className}>{children}</body>
        </html>
    )
}
